//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newbarbershop
{
    using System;
    using System.Collections.Generic;
    
    public partial class grafik
    {
        public int id_zmiany { get; set; }
        public int id_pracownika { get; set; }
        public System.DateTime data { get; set; }
        public System.TimeSpan od_godziny { get; set; }
        public Nullable<System.TimeSpan> do_godziny { get; set; }
    
        public virtual pracownicy pracownicy { get; set; }
    }
}
